version: '3.8'
services:
  invoice-parser:
    container_name: invoice-parser
    build: .
    ports:
      - "80:4444"
    volumes:
      # WICHTIG: Die Config-Datei muss auf dem Host existieren!
      # Touch sie vorher auf dem Host, sonst erstellt Docker einen Ordner.
      - ./configs:/app/configs
    restart: unless-stopped